service: todo-list

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, "dev"}
  region: ${opt:region, "us-west-1"}
  logs:
    restApi: true
  lambdaHashingVersion: 20201221
  environment:
    REGION: ${self:provider.region}
    tableName: ${self:custom.tableName}
  # eventBridge:
  #   useCloudFormation: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:BatchWriteItem
          Resource: !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${self:custom.tableName}
        - Effect: Allow
          Action: 
            - events:PutEvents
            - events:listEventBuses
          Resource: !Sub arn:aws:events:${AWS::Region}:${AWS::AccountId}:event-bus/*

package:
  patterns:
    - '!resources/**'

custom:
  tableName: todo-list-${self:provider.stage}
  todoCognitoName: ${self:service}-cognito

functions:
  todo-create:
    handler: src/create.handler
    events:
      - http:
          path: /create
          method: POST
    environment:
      EVENT_BRIDGE: "default"
  
  dynamodb-crud:
    handler: src/dynamodb-crud.handler
    events:
      - eventBridge:
          pattern:
            source: # rule
              - Todo
            detail-type:
              - dynamodb-crud

  # todo-update:
  #   handler: update.handler
  #   events:
  #     - http:
  #         path: /update/{id}
  #         method: put

  # todo-delete:
  #   handler: delete.handler
  #   events:
  #     - http:
  #         path: /delete/{id}
  #         method: delete
  
  # todo-search:
  #   handler: search.handler
  #   events:
  #     - http:
  #         path: /search
  #         method: get

plugins:
  - serverless-webpack
