service: todo-list
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  profile: nadtakan
  stage: ${opt:stage, "dev"}
  region: ${opt:region, "us-west-2"}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: arn:aws:dynamodb:us-west-2:*:*

package:
    individually: true

custom:
  tableName: todo-list-${self:provider.stage}
  todoCognitoName: ${self:service}-cognito

functions:
  todo-create:
    handler: create.handler
    events:
      - http:
          path: /create
          method: post

  todo-update:
    handler: update.handler
    events:
      - http:
          path: /update/{id}
          method: put

  todo-delete:
    handler: delete.handler
    events:
      - http:
          path: /update/{id}
          method: delete
  
  todo-list:
    handler: search.handler
    events:
      - http:
          path: /update/{id}
          method: delete

plugins:
  - serverless-webpack
