service: todo-list
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  profile: nadtakan
  stage: ${opt:stage, "dev"}
  region: ${opt:region, "us-west-1"}
  logs:
    restApi: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: !Sub arn:aws:dynamodb:${AWS::Region:${AWS::AccountId}:table/${self:custom.tableName}

package:
  individually: true

custom:
  tableName: todo-list-${self:provider.stage}
  todoCognitoName: ${self:service}-cognito

functions:
  todo-create:
    handler: create.handler
    events:
      - http:
          path: /create
          method: post

  # todo-update:
  #   handler: update.handler
  #   events:
  #     - http:
  #         path: /update/{id}
  #         method: put

  # todo-delete:
  #   handler: delete.handler
  #   events:
  #     - http:
  #         path: /delete/{id}
  #         method: delete
  
  # todo-search:
  #   handler: search.handler
  #   events:
  #     - http:
  #         path: /search
  #         method: get

plugins:
  - serverless-webpack
