service: todo-list

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, "dev"}
  region: ${opt:region, "us-west-1"}
  logs:
    restApi: true
  lambdaHashingVersion: 20201221
  environment:
    REGION: ${self:provider.region}
    FAILURE_SNS: 
      Fn::ImportValue: ${self:custom.todoSnsStack}:${self:provider.stage}:SNSTargetNotifyForFailedEvents
    TABLE_NAME: ${self:custom.tableName}
    EVENT_BRIDGE: "default"
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:BatchWriteItem
          Resource: !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${self:custom.tableName}
        - Effect: Allow
          Action: 
            - events:PutEvents
            - events:listEventBuses
          Resource: !Sub arn:aws:events:${AWS::Region}:${AWS::AccountId}:event-bus/*

package:
  patterns:
    - '!resources/**'
    - '!mocks/**'

custom:
  tableName: todo-list-${self:provider.stage}
  todoCognitoName: ${self:service}-cognito
  todoSnsStack: todo-list-sns-${self:provider.stage}

functions:
  catch-all:
    handler: src/hanlders/catch-all.handler
    events:
      - http:
          path: /{any+} # this matches any path, the token 'any' doesn't mean anything special
          method: ANY      
  
  todo-create:
    handler: src/hanlders/create.handler
    events:
      - eventBridge:
          pattern:
            source: # rule
              - source.events
            detail-type:
              - create

  todo-update:
    handler: src/hanlders/update.handler
    events:
      - eventBridge:
          pattern:
            source: # rule
              - source.events
            detail-type:
              - update

  todo-delete:
    handler: src/hanlders/delete.handler
    events:
      - eventBridge:
          pattern:
            source: # rule
              - source.events
            detail-type:
              - delete
  
  todo-search:
    handler: src/hanlders/search.handler
    events:
      - eventBridge:
          pattern:
            source: # rule
              - source.events
            detail-type:
              - search

plugins:
  - serverless-webpack
