service: todo-list-cognito-userpool
frameworkVersion: '2'

provider:
  name: aws
  stage: ${opt:stage, "dev"}
  region: ${opt:region, "us-west-1"}

resources:
  Resources:
    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: ${self:service}-${self:provider.stage}-user-pool
        AliasAttributes:
          - email
        AutoVerifiedAttributes:
          - email
        Schema:
          - Name: email
            AttributeDataType: String
            Mutable: true
            Required: true

    CognitoUserPoolClientWeb:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: ${self:provider.stage}-user-pool-client-web
        UserPoolId:
          Ref: CognitoUserPool
        GenerateSecret: false
        ExplicitAuthFlows:
          - ADMIN_NO_SRP_AUTH

  Outputs:
    UserPoolId:
      Value:
        Ref: CognitoUserPool
      Export:
          Name: ${self:service}:${self:provider.stage}:UserPoolId
    
    UserPoolArn:
      Value: 
        Fn::GetAtt:
          - CognitoUserPool
          - Arn
      Export:
        Name: ${self:service}:${self:provider.stage}:UserPoolArn
