service: todo-list-dynamodb
frameworkVersion: '2'

provider:
  name: aws
  profile: nadtakan
  stage: ${opt:stage, "dev"}
  region: ${opt:region, "us-west-1"}

custom:
  tableName: todo-list-${self:provider.stage}

resources:
  Resources:
    restaurantsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
