name: Develop Deployment

on:
  push:
    branches: 
      - develop

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.19'
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
        
      - name: install
        run: npm install

      - name: install serverless framework
        run: npm i serverless -g

      # - name: test
      #   run: npm test
      
      - name: deploy
        run: sls deploy -v --stage dev
        
